# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

permissions:
  contents: read  # Allow the workflow to read the repository contents

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dotnet-version: [ '9.0.x' ] # use .NET SDK 9.0

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore Datadog.Serverless.Tests/Datadog.Serverless.Tests.csproj

    - name: Build
      run: dotnet build Datadog.Serverless.Tests/Datadog.Serverless.Tests.csproj --no-restore

    - name: Test
      run: dotnet test Datadog.Serverless.Tests/Datadog.Serverless.Tests.csproj --no-build --verbosity normal
