name: Publish packages on Nuget

on:
  workflow_dispatch:
    inputs:
      publish-package:
        description: "Build or Build and Publish?"
        required: true
        type: choice
        default: "Build"
        options:
          - "Build"
          - "Build and Publish"

permissions: {}

jobs:
  downloadbinaries:
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.package.outputs.package-version }}
      serverless-compat-version: ${{ steps.serverlesscompatbinary.outputs.serverless-compat-version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: package
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
            echo "Invalid tag format: $GITHUB_REF, must be in the form vMAJOR.MINOR.PATCH"
            exit 1
          fi
          PACKAGE_VERSION="${GITHUB_REF#refs/tags/v}"

          echo "package-version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
      - id: serverlesscompatbinary
        run: |
          RESPONSE=$(curl -s "https://api.github.com/repos/datadog/serverless-components/releases")
          SERVERLESS_COMPAT_VERSION=$(echo "$RESPONSE" | jq -r --arg pattern "datadog-serverless-compat\/v[0-9]*\.[0-9]*\.[0-9]*" '.[] | select(.tag_name | test($pattern)) | .tag_name' | sort -V | tail -n 1)

          echo "Using version ${SERVERLESS_COMPAT_VERSION} of Serverless Compatibility Layer binary"
          echo "serverless-compat-version=$(echo "$SERVERLESS_COMPAT_VERSION" | jq -rR 'ltrimstr("sls-")')" >> "$GITHUB_OUTPUT"

          curl --output-dir ./temp/ --create-dirs -O -s -L "https://github.com/DataDog/serverless-components/releases/download/${SERVERLESS_COMPAT_VERSION}/datadog-serverless-compat.zip"
          unzip ./temp/datadog-serverless-compat.zip -d ./Datadog.Serverless/datadog
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: bin
          path: Datadog.Serverless/datadog/bin
  build:
    needs: [downloadbinaries]
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ needs.downloadbinaries.outputs.package-version }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: Datadog.Serverless/datadog
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 #4.3.1
        with:
          dotnet-version: "9.0.x"
      - run: cd Datadog.Serverless && dotnet pack -p:Version=${{ env.PACKAGE_VERSION }} -c Release
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: build
          path: Datadog.Serverless/bin/Release/Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.nupkg
  publish:
    if: ${{ github.event.inputs.publish-package == 'Build and Publish' }}
    needs: [downloadbinaries, build]
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ needs.downloadbinaries.outputs.package-version }}
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: build
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 #4.3.1
        with:
          dotnet-version: "9.0.x"
      - run: dotnet nuget push Datadog.Serverless.Compat.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
  release:
    if: ${{ github.event.inputs.publish-package == 'Build and Publish' }}
    runs-on: ubuntu-latest
    needs: [downloadbinaries, build, publish]
    permissions:
      contents: write
    env:
      PACKAGE_VERSION: ${{ needs.downloadbinaries.outputs.package-version }}
      SERVERLESS_COMPAT_VERSION: ${{ needs.downloadbinaries.outputs.serverless-compat-version }}
    steps:
      - uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          body: "Uses [${{ env.SERVERLESS_COMPAT_VERSION }}](https://github.com/DataDog/serverless-components/releases/tag/${{ env.SERVERLESS_COMPAT_VERSION }}) of the Serverless Compatibility Layer binary."
          draft: true
          tag_name: "v${{ env.PACKAGE_VERSION }}"
          generate_release_notes: true
          make_latest: true
